// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateOutbox(ctx context.Context, arg CreateOutboxParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
